version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: direct
      
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
